version: '3.7'

services:
  mk-crew-db:
    container_name: mk-crew-db
    image: postgres:15
    ports:
      - ":5432"
    user: postgres
    environment:
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mk-crew-db:/var/lib/postgresql/data



  mk-crew-api:
    container_name: mk-crew-api
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    depends_on:
      mk-crew-db:
        condition: service_healthy
    ports:
      - "8001:8000"
    restart: unless-stopped



volumes:
  mk-crew-db:

