version: '3.7'

services:
  mk-crew-db:
    container_name: mk-crew-db
    image: postgres:15
    ports:
      - "5433:5432"
    user: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mk-crew-db:/var/lib/postgresql/data

  mk-crew-api:
    container_name: mk-crew-api
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=mk-crew-db
      - DATABASE_PORT=5432
    depends_on:
      mk-crew-db:
        condition: service_healthy
    ports:
      - "8001:8000"
    restart: unless-stopped

volumes:
  mk-crew-db: