name: Test Django Basic

on:
#  workflow-dispatch:
#  schedule:
#    - cron: '30 15 * * * '
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set Up Django Secret Key
        run: |
          echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Install Requirements
#        working-directory: ./
        run: | 
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt

      - name: Django Run Server
        run: |
          python manage.py runserver